# -*- coding: utf-8 -*-
"""Learn OpenAI SDK - TogetherAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCugXGZQvYH0tGmGTwcab2GJLIc8s8w1

## **Nhớ bấm ô trên cùng để cài openai nha!**
"""

# !pip install openai

from openai import OpenAI

# Nếu các bạn dùng TogetherAI
client = OpenAI(
    base_url="https://api.together.xyz/v1",
    # Làm theo hướng dẫn trong bài, truy cập https://api.together.ai/settings/api-keys để lấy API Key nha
    api_key='xxxxx',
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Hello. Mày là ai vậy bot?",
        }
    ],
    model="meta-llama/Llama-3-70b-chat-hf",
)

print(chat_completion.choices[0].message.content)

stream = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Hello. Who are you? Write me a long poem to introduce your self.",
        }
    ],
    model="meta-llama/Llama-3-70b-chat-hf",
    stream=True
)

for chunk in stream:
    print(chunk.choices[0].delta.content or "", end="")