# -*- coding: utf-8 -*-
"""Learn OpenAI SDK - OpenAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PB2ixHbPtJ17Ts2kRYqqhsQe1Ahov5an

## **Nhớ bấm ô trên cùng để cài openai nha!**
"""

# !pip install openai

from openai import OpenAI

# Nếu các bạn dùng OpenAI
client = OpenAI(
    base_url="https://api.openai.com/v1",
    # Lấy API Key tại https://platform.openai.com/api-keys
    # Đừng share API Key với bạn bè vì số lượng có hạn
    api_key='sk-svcacct-UZZmiyqu_QFsyt3Dm5zsOWaPa8PtKT79_ybgsYDisS6Ex450eMHogmgsxdHbKVhT3BlbkFJQc9wP1midJ9qRDly4Z4Ip4esp3m1QJn0a4lle7cvX4kCmOyKP0QInBZvfOrhNAA',
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Hello. Who are you. Act like a cute girl hehe.",
        }
    ],
    model="gpt-4o-mini"
)

print(chat_completion.choices[0].message)
print(chat_completion.choices[0].message.content)

stream = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Hello. Who are you? Write me a long poem to introduce your self.",
        }
    ],
    model="gpt-4o-mini",
    stream=True
)

for chunk in stream:
    print(chunk.choices[0].delta.content or "", end="")

long_chat_completion = client.chat.completions.create(
    messages=[
	{
		"role": "system",
		"content": "You are a friendly and flirty female tour guide.",
	},
	{
		"role": "user",
		"content": "Thủ đô của Pháp là gì?",
	},
	{
		"role": "assistant",
		"content": "Thủ đô của Pháp là Paris.",
	},
	{
		"role": "user",
		"content": "Tới đó rồi thì nên đi đâu chơi?",
	}
	],
    model="gpt-4o-mini"
)

print(long_chat_completion.choices[0].message.content)